### ISSUE TITLE
File is "locked"

### ISSUE THREAD

**Issue by ExaconAT** [newroco/W2G2#11]
But every one can write in the file / directory?

**Comment by orzuionut** [comment]
Can you give more details?

**Comment by ExaconAT** [comment]
When i click on the lock icon it shows "gesperrt durch (User)" / locked by (User). But when i login as an other user the file can be edited normally.

16.04.3 LTS
Apache/2.4.18 (Ubuntu)
mysql  Ver 15.1 Distrib 10.0.33-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Nextcloud 13 + LDAP

**Comment by orzuionut** [comment]
We will release a new version. Please update the app when done and check if the issue persists.

**Comment by ExaconAT** [comment]
Ok thanks

**Comment by putt1ck** [comment]
For interest, does the lock show in the locked files list in the admin view?

**Comment by ExaconAT** [comment]
Hello,

where ist he locked files list?

BR

Von: Chris Puttick [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. März 2018 06:44
An: newroco/W2G2 <W2G2@noreply.github.com>
Cc: René Hofmann <rh@exacon.at>; Author <author@noreply.github.com>
Betreff: Re: [newroco/W2G2] File is "locked" (#11)


For interest, does the lock show in the locked files list in the admin view?

**Comment by putt1ck** [comment]
In Settings -> Administration/Additional Settings, near the bottom - you should see a number of options related to locking, including a list of any locked files (and if there are none a statement like "There are no locked files at the moment").

**Comment by ExaconAT** [comment]
Shows correct output?

BR

Von: Chris Puttick [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. März 2018 08:38
An: newroco/W2G2 <W2G2@noreply.github.com>
Cc: René Hofmann <rh@exacon.at>; Author <author@noreply.github.com>
Betreff: Re: [newroco/W2G2] File is "locked" (#11)


In Settings -> Administration/Additional Settings, near the bottom - you should see a number of options related to locking, including a list of any locked files (and if there are none a statement like "There are no locked files at the moment").

**Comment by Emi94** [comment]
@ExaconAT Did you update the app to version 1.1.0?

If not, what does the file path look like? Does it have a special character like "&"? In versions prior to 1.1.0 the file path has been used for locks and some special characters lead to locks not to be visible.

The latest version (1.1.0) moved to file IDs which fixes this issue.

**Comment by ExaconAT** [comment]
Sorry didnt see the update, now i’m on v. 1.1.0 but:


Von: Emilian Mitocariu [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. März 2018 09:09
An: newroco/W2G2 <W2G2@noreply.github.com>
Cc: René Hofmann <rh@exacon.at>; Mention <mention@noreply.github.com>
Betreff: Re: [newroco/W2G2] File is "locked" (#11)


@ExaconAT<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_exaconat&d=DwMFaQ&c=k8YJ84Y2YEMo5BmkG-FRKlhXpB6ifmQmz0tZEfnu3PM&r=lL8vrlW7JuBUyVlkSXRKg-fYwkz2gHAY_iEyexQx1I8&m=zqRd6Qtf7ptQncXL1g7go3S-Pv2Z_UW7fy0TgVptOjE&s=u7WHgA2HXmmOcwvwJsmpyna6ZZ66ECnZP8LjOdeZ99c&e=> Did you update the app to version 1.1.0?

If not, what does the file path look like? Does it have a special character like "&"? In versions prior to 1.1.0 the file path has been used for locks and some special characters lead to locks not to be visible.

The latest version (1.1.0) moved to file IDs which fixes this issue.

**Comment by ExaconAT** [comment]
Reinstalling makes the same problem

Von: Emilian Mitocariu [mailto:notifications@github.com]
Gesendet: Donnerstag, 15. März 2018 09:09
An: newroco/W2G2 <W2G2@noreply.github.com>
Cc: René Hofmann <rh@exacon.at>; Mention <mention@noreply.github.com>
Betreff: Re: [newroco/W2G2] File is "locked" (#11)


@ExaconAT<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_exaconat&d=DwMFaQ&c=k8YJ84Y2YEMo5BmkG-FRKlhXpB6ifmQmz0tZEfnu3PM&r=lL8vrlW7JuBUyVlkSXRKg-fYwkz2gHAY_iEyexQx1I8&m=zqRd6Qtf7ptQncXL1g7go3S-Pv2Z_UW7fy0TgVptOjE&s=u7WHgA2HXmmOcwvwJsmpyna6ZZ66ECnZP8LjOdeZ99c&e=> Did you update the app to version 1.1.0?

If not, what does the file path look like? Does it have a special character like "&"? In versions prior to 1.1.0 the file path has been used for locks and some special characters lead to locks not to be visible.

The latest version (1.1.0) moved to file IDs which fixes this issue.

**Comment by sopasc** [comment]
Hello All, 
Am getting the same issue. The file is locked but another user can still modified/rename/delete/etc with no problem.

Am willing to help fix this, I know a little bit of php, if someone shares some/any documentation as how this app works.

Meanwhile I'll see if I can find out what's wrong.

**Comment by sopasc** [comment]
FYI, I "fixed' this issue by uncommenting lines 203 and 205 from file w2g2.js

This will work as long as your language is english, otherwise it will not work.

**Comment by putt1ck** [comment]
Is this with latest version?
