### ISSUE TITLE
errors after update to latest vetsion :

### ISSUE THREAD

**Issue by CHazz** [newroco/W2G2#12]
0:08:17+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxxx","app":"index","method":"POST","url":"\/index.php\/apps\/w2g2\/ajax\/checkState.php","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM oc_locks_w2g2 WHERE file_id = ?' with params [\\\"11\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'file_id' in 'where clause'\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM o...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(71): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/lib\\\/Database.php(42): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/lib\\\/File.php(15): OCA\\\\w2g2\\\\Database::getFileLock('11')\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/lib\\\/CheckState.php(47): OCA\\\\w2g2\\\\File->__construct('11')\\n#6 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/lib\\\/CheckState.php(35): OCA\\\\w2g2\\\\CheckState->check('11', 'dir')\\n#7 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/ajax\\\/checkState.php(12): OCA\\\\w2g2\\\\CheckState->handle()\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#9 [internal function]: OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(Closure), Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/w2g2\\\/ajax...')\\n#12 \\\/var\\\/www\\\/html\\\/index.php(37): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":71}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"2wXTuVdJpTNiA52P9GQF","level":3,"time":"2018-03-15T10:08:21+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxxx","app":"index","method":"POST","url":"\/index.php\/apps\/w2g2\/ajax\/updateDatabase.php","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\SyntaxErrorException\",\"Message\":\"An exception occurred while executing 'ALTER TABLE oc_locks_w2g2 RENAME COLUMN name TO file_id':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN name TO file_id' at line 1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'ALTER TABLE oc_...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(73): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/lib\\\/Migration\\\/UpdateDatabase.php(87): OC_DB_StatementWrapper->execute()\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/lib\\\/Migration\\\/UpdateDatabase.php(20): OCA\\\\w2g2\\\\Migration\\\\UpdateDatabase->update()\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/ajax\\\/updateDatabase.php(14): OCA\\\\w2g2\\\\Migration\\\\UpdateDatabase->run()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#7 [internal function]: OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/w2g2\\\/ajax...')\\n#10 \\\/var\\\/www\\\/html\\\/index.php(37): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":90}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}
{"reqId":"h1RTtZcw5PAg4nFJxf0V","level":3,"time":"2018-03-15T10:08:25+01:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxxx","app":"index","method":"POST","url":"\/index.php\/apps\/w2g2\/ajax\/updateDatabase.php","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\SyntaxErrorException\",\"Message\":\"An exception occurred while executing 'ALTER TABLE oc_locks_w2g2 RENAME COLUMN name TO file_id':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN name TO file_id' at line 1\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'ALTER TABLE oc_...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(73): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/lib\\\/Migration\\\/UpdateDatabase.php(87): OC_DB_StatementWrapper->execute()\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/lib\\\/Migration\\\/UpdateDatabase.php(20): OCA\\\\w2g2\\\\Migration\\\\UpdateDatabase->update()\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/w2g2\\\/ajax\\\/updateDatabase.php(14): OCA\\\\w2g2\\\\Migration\\\\UpdateDatabase->run()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Route.php(155): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#7 [internal function]: OC\\\\Route\\\\Route->OC\\\\Route\\\\{closure}(*** sensitive parameters replaced ***)\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(998): OC\\\\Route\\\\Router->match('\\\/apps\\\/w2g2\\\/ajax...')\\n#10 \\\/var\\\/www\\\/html\\\/index.php(37): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":90}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.186 Safari\/537.36","version":"13.0.0.14"}

**Comment by Emi94** [comment]
This might be a cache problem. Can you refresh while on nextcloud with CTRL+F5?

**Comment by Emi94** [comment]
Actually in your case it's because you use MariaDB and the app was tested on PostgreSQL

**Comment by DJCrashdummy** [comment]
after update to 1.1.0 i have got a similar problem...
- yes, i've done a refresh, but it has no effect 
- my hoster also uses MySQL

maybe this regression should be mentioned anywhere, because after the update to W2G2 1.1.0...
- file/folder locking no more works
- i'm also unable to access the additional admin-settings. i only get an internal server error!

**Comment by Patt92** [comment]
your table uses an old scheme.
Run either:
DROP table oc_locks_w2g2

or:
ALTER table oc_locks_w2g2 add column file_id int before path

Syntax unchecked, but you should be able to understand the meaning.
The DB system doesn't matter. The second one leaves the primary key wrong, so I recommend simply dropping the table and getting it recreated as it should

**Comment by DJCrashdummy** [comment]
thanks @Patt92, i doped the whole table and it works like a charm (even i had to use a GUI on a shared hoster).
you are right... although it is a plain NC13 installation (for testing) maybe i also messed around with Working2gether and therefor got the wrong scheme.
