### ISSUE TITLE
Make unlocking multiple files make more sense

### ISSUE THREAD

**Issue by putt1ck** [newroco/W2G2#2]
Right now can select multiple files in the admin interface for unlocking, but clicking the "unlock file" button only unlocks the first selected; should either allow multiple entries to be unlocked when selected, or not allow multiple selections. Probably the latter, from a risk perspective; an accidental unlock outweighs having to click a few on the rare occasions multiple files need unlocking.

**Comment by orzuionut** [comment]
Updated with the second option.
