### ISSUE TITLE
Failed migration

### ISSUE THREAD

**Issue by Shinrai** [newroco/W2G2#26]
I gave you a pull request #23. You literally copied the code, committed it.

Quite bad form to take someone else's work and claim it as your own. See commit c34a38d52c9ff53303a21e4dc7cea86a81907b87 (2018-04-10) and pull request #23 (2018-04-05) as reference.

Then rewrote it all into the jumbled mess it is now. Your code doesn't do what you were originally intending to do. Which was track the locks by the file_id instead of by name, Instead you now have code executing thinking it should upgrade all the time. And further more will error every time.

I'd suggest just reverting back and accepting the pull request. Was not only working correctly but did it in a much cleaner fashion.

Details below:

```PHP
    protected function isOldVersion()
    {
        $query = "SELECT column_name
                  FROM information_schema.columns
                  WHERE table_name = '" . $this->tableName . "' and column_name = 'name'";

        $result = $this->db->executeQuery($query)
            ->fetchAll();

        return is_array($result) && count($result) > 0;
    }
```

the column_name "name" will always be present as you are never changing it nor creating the tmp table with the file_id column in the first place.

See code:

```PHP
    protected function createTempTable()
    {
        $createStatement = "CREATE TABLE " . $this->tempTableName . " (name varchar(255) PRIMARY KEY, created TIMESTAMP DEFAULT CURRENT_TIMESTAMP, locked_by varchar(255))";

        $this->db->executeQuery($createStatement);
    }
```

Notice the first column. No where is it present you change the column.

In fact you drop the old table:
```PHP
    protected function dropOldTable()
    {
        $dropStatement = "DROP TABLE " . $this->tableName;

        $this->db->executeQuery($dropStatement);
    }
```

Then try to insert into it after it's been dropped without recreating it:
```PHP
    protected function insertDataFromTempTable()
    {
        $files = $this->getLockedFiles();

        if (count($files) <= 0) {
            return;
        }

        // Add the data back in the table
        $insertQuery = "INSERT INTO " . $this->tableName . " (file_id, locked_by) VALUES ";

        $len = count($files);
        for ($i = 0; $i < $len; $i++) {
            $insertQuery .= "('" . $files[$i]['id'] . "', '" . $files[$i]['locked_by'] . "')";

            // Add a trailing comma if not the last one.
            if ($i != $len - 1) {
                $insertQuery .= ', ';
            }
        }

        $this->db->executeQuery($insertQuery);
    }
```

**Comment by DekoLP** [comment]
So it isnt fixed yet?

**Comment by Shinrai** [comment]
No it’s not. The current master will error out trying to insert into a table that was dropped.

**Comment by orzuionut** [comment]
I'm leveraging the Nextcloud's 'repair steps'. First I created the temporary table to store the file locks until the new table is created by Nextcloud from the 'database.xml' file, then on the next 'repair step' the app imports the file locks into the newly created table from the old, temporary one, then drops it.

**Comment by Shinrai** [comment]
That’s funny considering you copy pasted my pull request into your master and committed it. Again see commit c34a38d52c9ff53303a21e4dc7cea86a81907b87

This isn’t the first time you’ve closed a pull request yet took the code from the pull request.

As far as the rename that’s an easy fix simply change that line to 

```
$renameQuery = "ALTER TABLE  " . $this->TMPtableName . " RENAME TO " . $this->tableName . "";
```

**Comment by orzuionut** [comment]
Yes, I've tried your code on a dev branch but it didn't work. And even if it did it wasn't the best solution, I've considered that the 'repair steps' approach was the best.
