### ISSUE TITLE
Should not be using Mysql 5.6.5+ Features.

### ISSUE THREAD

**Issue by Shinrai** [newroco/W2G2#28]
Per https://docs.nextcloud.com/server/10/admin_manual/installation/system_requirements.html
```
Databases: MySQL/MariaDB 5.5+; PostgreSQL 9.x (10 is supported with Nextcloud 13+); Oracle 11g (currently only possible if you contact us <https://nextcloud.com/enterprise> as part of a subscription)
```

Should not be using Mysql 5.6.5+ Features.

```
octrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_locks_w2g2 CHANGE `file_id` `file_id` BIGINT UNSIGNED NOT NULL, CHANGE `locked_by` `locked_by` VARCHAR(255) NOT NULL, CHANGE `created` `created` DATETIME DEFAULT CURRENT_TIMESTAMP': SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created'
```

**Comment by hypervtechnics** [comment]
This occurs for me when trying to install the app. Doesn't work. Will this be fixed?

**Comment by Shinrai** [comment]
After wiping anyone's database of file locks in an untested update to the Nextcloud app store, A fix was given to the repo owner. 

He went off and fixed it a different way after copy pasting my code into the repo rather than merging. According to him due to my form of renaming a table, which was not compatible with PostgreSQL. Which when made present of it I responded with a fix for that.

But has left this incompatibility open for over a month. Seems like this repo is a low priority hobby.

See issue #26

**Comment by hypervtechnics** [comment]
Is your fork working/does not have this issue?
