### ISSUE TITLE
High CPU load on Nextcloud 13

### ISSUE THREAD

**Issue by err0x5dd** [newroco/W2G2#29]
In this Nextcloud issue [#9042](https://github.com/nextcloud/server/issues/9042) it was discovered that this app creates a high cpu load for the mysql process. Please take a look at that.

**Comment by dohlin** [comment]
Additional info: this appears to have started with v1.1.1 either my testing...in v1.1.0 I didn't have the issue.

**Comment by Schmuuu** [comment]
There is another user who discovered this issue:
https://help.nextcloud.com/t/nextcloud-performance/28720/7?u=schmu

With this app enabled, the CPU load goes through the roof and the server becomes pretty much unresponsive for quite a while.
He found out, that disabling this app results in a fast and responsive server again. 
So this issue has a high business impact.

**Comment by mtappgit** [comment]
Perhaps my issue was the same:

**mysql and php-fpm7.0  use 50% cpu each**
I got warnings about memory consumption in Safari.

**mysql is flooded with "SELECT * FROM oc_filecache WHERE fileid = NULL"**

I found the query in FileMapper ->  get($fileId). (w2g2/lib/Db/FileMapper.php)
The function does not check for null fieldId.

But the main Problem was in LockService -> check($fileId, $fileType)  (w2g2/lib/Service/LockService.php)

Line 150, the loop has no sanity check and does not break if some upper directory becomes null:

    while ($currentDirectoryData['path'] !== 'files' && $currentDirectoryData['path'] !== '__groupfolders') {


I added   "**_$currentDirectoryData  &&_**"    to the while condition:

    while ($currentDirectoryData  &&  $currentDirectoryData['path'] !== 'files' && $currentDirectoryData['path'] !== '__groupfolders') {


For me this works.

**Comment by putt1ck** [comment]
This issue seems no longer to be present.
