### ISSUE TITLE
Improve README by explaining "locking"

### ISSUE THREAD

**Issue by fwolfst** [newroco/W2G2#31]
I am still unsure what locking exactly should mean in the context of this app. I assume it means nobody except the "lock-holder" can modify the data in any way. As this does not match my (small) experiences with this app, it would be cool if the README is a bit more precise of what the App tries to achieve. I would make a PR if I knew it :)

**Comment by CleanaZ** [comment]
I also would very much appreciate it if you can clearly explain what the locking feature/app should be able to do (or not to do). Either your intention is something other than we (normal) user are expecting or there are some bugs with the app.

**Comment by orzuionut** [comment]
Added section in README.
