### ISSUE TITLE
W2G2  2.0.5  NC 13.0.4.0 : display issue 

### ISSUE THREAD

**Issue by ledshark24** [newroco/W2G2#32]
Hi,

I just installed the plugin on a freshly upgraded to  13.0.4.0 install, I can lock files (not sure of the effect) but the display is all wrong (see included screenshot) : 
-  icons are not on the right place
- strange icons below the last file
- and no text "locked by" is to be seen. 

![w2g2](https://user-images.githubusercontent.com/1142671/41317581-e601d7ca-6e95-11e8-8849-e7a5f7d2f8e5.png)

Rapid html inspection shows that some elements are present but not at the right place ? Seems to be a CSS issue to me. I tried to fiddle with the span classes but no luck.

**Comment by DBJRdev** [comment]
Same problem here, but with an upgrade install to 13.0.4

**Comment by ledshark24** [comment]
Hey,
Put some more work on the css side of things, we are testing [this fix](https://github.com/ledshark24/W2G2/commit/973550e3c72b96daaf398df220b317270fd4e8d3)  that looks like OK... Not 100% certain yet. More feedback to come later.

**Comment by grivalta** [comment]
Hi,
only a rapid work around for users (in this situation it's impossible to unlock by the GUI a locked file): You can press dx mouse button ("Files Right Click" app needs to be previously installed) and click on "Details" and "Sharing" tab (or directly on "Share file" on contextual menu). You can see that the file row is now apparently unlocked, but it's false (when you refresh the page the row is always locked). But after Details>Sharing choose, you can click on the lock icon to unlock the file. I hope this can help...

**Comment by postilion** [comment]
FYI  @ledshark24 patch works for us with app v2.0.5 and NC v13.0.4.  Thanks for the fix! :-)
-nic

**Comment by orzuionut** [comment]
@ledshark24  do you want to make a pull request or do you want me to integrate it myself?

**Comment by ledshark24** [comment]
Please do so, I embarrassed myself enough when I tried it...

**Comment by orzuionut** [comment]
Updated with the fix. Thank you @ledshark24

**Comment by orzuionut** [comment]
The update will be included in the next release. It will be made soon
