### ISSUE TITLE
W2G2 version 2.0.5 and Nextcloud 13.0.5

### ISSUE THREAD

**Issue by ndecaris** [newroco/W2G2#34]
hello folks,

we can't use W2G2. when we lock a directory, even the owner can't access to this directory.
the directory  change of color and we can't even read it name.

any idea ??

thanks in advance
Nicolas

**Comment by DBJRdev** [comment]
Same as W2G2 2.0.5 NC 13.0.4.0 : display issue #32, I would say. They seem to have a fix ready, but not released yet. We are also waiting for it eagerly.

**Comment by orzuionut** [comment]
Fixed it. After we release the next version please update the plugin.
