### ISSUE TITLE
Error during update from 2.0.5 to 2.0.6

### ISSUE THREAD

**Issue by radoeka** [newroco/W2G2#35]
Received the following error during update from 2.0.5 to 2.0.6

{"reqId":"bRT5AjWGc89ILoQiOnOQ","level":3,"time":"2018-08-08T11:50:12+02:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--",
"message":"\\OC\\Updater::failure: Doctrine\\DBAL\\Exception\\TableNotFoundException: An exception occurred while executing 'SELECT column_name\n                  FROM information_schema.columns\n                  WHERE table_name = 'oc_locks_w2g2' and column_name = 'name'':\n\nSQLSTATE[HY000]: General error: 1 no such table: information_schema.columns","userAgent":"--","version":"13.0.5.2"}

The database does not have a table called information_schema.columns

This is at NC 13.0.5
Apache
php-7.0
sqlite3
linux

`# echo ".tables" | sqlite3 owncloud.db | grep w2g`
oc_locks_w2g                 oc_vcategory               
oc_locks_w2g2                oc_vcategory_to_object     

I disabled w2g2 (and removed) to be able to keep nextcloud running.

Can I safely remove the tables shown above?

Once both tables have been removed, can I install w2g2 again?

**Comment by orzuionut** [comment]
Sorry, we don't support SQLite at the moment. Nextcloud, right now, informs about SQLite: "only recommended for testing and minimal-instances".
