### ISSUE TITLE
can't use on mariadb

### ISSUE THREAD

**Issue by Jock-TNT** [newroco/W2G2#37]
netxcloud version: nextcloud-13.0.5
mariadb version: 5.5.60
php version:7.2
An exception occurred while executing 'CREATE TABLE `oc_locks_w2g2` (`file_id` BIGINT UNSIGNED NOT NULL, `locked_by` VARCHAR(255) NOT NULL, `created` DATETIME DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(`file_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created'

I try to set sql_mode="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
but it still not work

**Comment by JankoMat** [comment]
In case you still haven't figured it out, I just stumbled across this post and I had the same problem when I first tried installing it.

You need to update your MariaDB installation as the app uses DATETIME which was added it 10.0.1: https://mariadb.com/kb/en/library/datetime/

Following this tutorial should tell you how to update if you don't know how to do it: https://www.zerostopbits.com/how-to-upgrade-mariadb-5-5-to-mariadb-10-3-on-centos-7-5-1804/

**Comment by orzuionut** [comment]
The default value for the 'created' column is now NULL so MariaDB 5.5 is supported.
