### ISSUE TITLE
Possible to lock but still read?

### ISSUE THREAD

**Issue by bigjohnsull** [newroco/W2G2#40]
Hi,
I'm using the W2G app with Nextcloud, and the lock stops ALL actions on the file (open, edit, download).

Would it be possible to introduce a change, or even a second type of lock, allowing a file to be locked from editing only, but still be readable?

Example:
User A locks file. User A can still perform all actions on the file - open, edit, download.
User B can see the lock, and can click the file, opening it in read only mode. They can view the locked file, but not edit it.
When User A unlocks the file, User B receives a notification onscreen, or can reopen the file, allowing them to edit because there's no longer a lock by another user.

**Comment by orzuionut** [comment]
Sorry, we don't plan on developing this feature yet.
