### ISSUE TITLE
Disable lock state on WebDAV connection

### ISSUE THREAD

**Issue by Bables55** [newroco/W2G2#43]
I recently knew of this application. I thought that it was convenient when using only on the Web browser. However, when mounting on Windows, data can be changed ignoring lock status.

In the case of a shared file, when a user other than the owner of the file changes and saves the data, the locked state is canceled and it is made independent of the file owned by the user. I do not think this behavior is problematic.
The problem is for locked data in the shared folder. In this case everyone can change the file. Is this impossible in terms of WebDAV specifications?
Is it possible to visually notice that the file is locked when connecting to WebDAV? Even if it is not actually locked.

**Comment by orzuionut** [comment]
Sorry, we don't support WebDAV locks and we don't plan on developing this feature yet.
