### ISSUE TITLE
W2G2 Nextcloud An exception occurred while executing 'CREATE TABLE `oc_locks_w2g2` 

### ISSUE THREAD

**Issue by manuelangelludena** [newroco/W2G2#44]
An exception occurred while executing 'CREATE TABLE `oc_locks_w2g2` (`file_id` BIGINT UNSIGNED NOT NULL, `locked_by` VARCHAR(255) NOT NULL, `created` DATETIME DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(`file_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created'

REMOVE "DEFAULT CURRENT_TIMESTAMP"

**Comment by Merodi** [comment]
Maybe you should Upgrade MariaDB 5 to 10

**Comment by orzuionut** [comment]
The default value for the 'created' column is now NULL so MariaDB 5.5 is supported.
