### ISSUE TITLE
Nextcloud 16 compatibility

### ISSUE THREAD

**Issue by madmath03** [newroco/W2G2#46]
Everything is in the title 😉

**Comment by Emi94** [comment]
@orzuionut I tested the app for NC 16 and the only problem I found was that I couldn't unlock a file from the admin panel. Can you take a look at it?

**Comment by DBJRdev** [comment]
@Emi94 : I can confirm - on NC 16.0.1 W2G2 works for the users. Similar to what was described by you, we were also unable to unlock single files from the admin panel. Yet the variant "unlock all" still works.

**Comment by ksteinb** [comment]
would please somebody look into the Nextcloud 16 issue?

**Comment by orzuionut** [comment]
We've released a new version which supports NC v16.
