### ISSUE TITLE
Exception occurred when enable W2G2 in NC 17

### ISSUE THREAD

**Issue by GlenHuf** [newroco/W2G2#52]
On a dev server with NC 17, I enable W2G2 app and it throws an exception while executing 'Insert Into' or 'Create table'.   See screenshots, the first one is after enabling the app, the second is after disable, remove, then enable again.  In these cases, the app is enabled if the page is refreshed.  No error occurs if app is NOT removed, only disabled and enabled again.  See server details attached.
![W2G2-error](https://user-images.githubusercontent.com/33641366/66519891-5cdcfa00-eaa5-11e9-831f-69f5e4af1046.png)

[2019-10-09.md.txt](https://github.com/newroco/W2G2/files/3709542/2019-10-09.md.txt)

**Comment by GlenHuf** [comment]
P.S. Even with these errors, the app does seem to function, the padlock is active for files and folders, I can enable and disable the lock.   The nextcloud install is upgraded from previous versions.

**Comment by MarkusKepert** [comment]
Create table issue is same like #63

**Comment by orzuionut** [comment]
Fixed with the new update.
