### ISSUE TITLE
Can't lock files in Nextcloud 21

### ISSUE THREAD

**Issue by Emi94** [newroco/W2G2#61]
When I press the lock next to a file it just blocks at the "In Progress" message. This is displayed in the logs on the admin panel:

![Opera Snapshot_2021-03-15_155108_devnc newro co](https://user-images.githubusercontent.com/11816318/111164057-58741500-85a6-11eb-8c15-149b55817eee.png)

**Comment by ctc** [comment]
nextcloud files_lock does not exist for Nextcloud 21 - w2g2 is based on its LockService.
https://github.com/nextcloud/files_lock/issues/38

**Comment by orzuionut** [comment]
Fixed with the new update.
