### ISSUE TITLE
SQL error when reinstalling the app on Nextcloud 21

### ISSUE THREAD

**Issue by Emi94** [newroco/W2G2#63]
If I remove the app and reinstall it from the Nextcloud interface I get the following error when I install it:

> An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "oc_locks_w2g2_temp" already exists

**Comment by MarkusKepert** [comment]
It only happen when you have a (failed) migration of lock data before. Fix is included in PR

**Comment by orzuionut** [comment]
I've merged the PR, thanks.
