### ISSUE TITLE
/appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead

### ISSUE THREAD

**Issue by Emi94** [newroco/W2G2#64]
When Nextcloud is in debug mode, the error from the title is displayed in the logs

**Comment by MarkusKepert** [comment]
app.php should migrated: https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html

It's not a showstopper for NC 21

**Comment by orzuionut** [comment]
Updated to use the new interface instead.
