### ISSUE TITLE
Endless Files update after W2G2 3.3.9 update

### ISSUE THREAD

**Issue by Tom582** [newroco/W2G2#69]
### Steps to reproduce
1. Update W2G2 from 3.3.8 to 3.3.9 under Nextcloud 24.0.1 (W2G2 settings are "display name" and "disable for directory")
2. After the update click on "Files" in the major toolbar

### Expected behaviour
After click on "Files" in the major toolbar, the recently edited files should be displayed clearly on the top of the main area and the files and directories in the home directory should be displayed immediately

### Actual behaviour
After click on "Files" in the major toolbar, shaded recently edited files are displayed but no other file or directory is displayed. Instead the hourglass circle is endlessly spinning

### Server configuration

**Operating system:**
Linux (as far as I know)

**Web server:**
n/a

**Database:**
unknown

**PHP version:**
unknown

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 24.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
n/a

**Where did you install Nextcloud from:**
I did not. My provider did.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Sorry, there is no such entry in the NextCloud environment provided by my provider.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Sorry, I do not have access.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

Sorry, not possible.
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
n/a

**Are you using encryption:** yes/no
n/a

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
n/a

### Client configuration
**Browser:**
Firefox 91.10.0esr

**Operating system:**
Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Sorry, not possible.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Sorry, not possible.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
n/a
```
</details>

**Comment by Emi94** [comment]
Note: version 3.3.9 doesn't bring anything new compared to 3.3.8 beside allowing it to be installed on NC 24 as in my initial tests it seemed to work just fine.

I've tested again with the settings you specified "(W2G2 settings are "display name" and "disable for directory")" and even tried to lock a file with a user that has no display name, but files still load fine. From your report it seems you are not the one who manages your instance of Nextcloud and don't know/have much access to things like logs/settings/package versions. I advise you contact your provider to take a look at your problem and come back with more info if your provider can't fix the issue themselves. There might be more info in the webserver or nextcloud logs.

PS: my test was done on Nextcloud 24.0.2, the latest version for 24 at the time of writing this message

**Comment by Tom582** [comment]
Thanks for your explanations, Emilian. I will contact my provider to see if he can help. If not I will wait for his 24.0.2 update, which should be due in short time and see, if this does the trick.

Apart from this issue, you may be interested to know, that I like your app and so far it performed as expected.

Regards
Tom

**Comment by Tom582** [comment]
Hi Emilian, I have contacted my provider and they ran some tests. Here is their feedback:

> We have investigated the problem. It turned out to be a frontend problem. Therefore, we did not find any entry in the log. However, in the browser console (F12) the following error is reported:
```
Uncaught (in promise) TypeError: e.vm is null
Path: webpack:///text/src/helpers/files.js line 173
```
> After disabling W2G2 the error is gone.

Hope this helps to narrow down and fix the problem.

Regards
Tom

**Comment by Tom582** [comment]
Maybe it is "just" a browser incompatibility?

- I noted the issue with firefox 91.11.0esr (64-bit).
- I cannot reproduce it with Chromium 101.0.4951.64

Regards
Tom

**Comment by Emi94** [comment]
I can reproduce this as well when using Firefox 102.0

I'll let one of the devs know about this issue

**Comment by rcarjan** [comment]
Hello. I have looked over this issue and it appears to come from the `nextcloud/text` app, not from W2G2. The issue has been raised on their repo over here: https://github.com/nextcloud/server/issues/32582

As per the comments, a fix has been proposed and will go live on the next maintenance release of nextcloud 24. (Which seems to be 24.0.3 at the moment, although this still needs to be confirmed).

In the meantime, there are two files which need to be changed in order to fix this issue: `apps/text/js/text-files.js` and `apps/text/js/text-files.js.map`. The files should be updated to the following contents:  

- [text-files.js](https://github.com/nextcloud/text/blob/ecb59d2de1e5cad00777d92c64a780a14d98168f/js/text-files.js)
- [text-files.js.map](https://github.com/nextcloud/text/blob/ecb59d2de1e5cad00777d92c64a780a14d98168f/js/text-files.js.map)

**Comment by Tom582** [comment]
Thanks for letting me know. I have checked the effect of both apps W2G2 and nextcloud/text in my nextcloud installation 24.0.1 and can confirm that the issue is related to nextcloud/text rather than W2G2.

Thanks for you help.

Looking forward to NextCloud 24.0.3.
Tom
